// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by Mobile.BuildTools.
//
//      Changes to this file may cause incorrect behavior and will be lost when 
//      the code is regenerated. 
//
//      This file should be excluded from source control.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Weigh.Helpers
{
    internal static class Secrets
    {
        internal const string AppCenter_iOS_Secret = "1896a8b5-81c0-4465-bab7-6141e9af0d97";

        internal const string AppCenter_Android_Secret = "1b6f9191-2285-4515-9730-f9b7592df27a";

        internal const string AppCenter_UWP_Secret = "";

        internal const string AppServiceEndpoint = "https://weigh.azurewebsites.net/";

        internal const string Admob_Banner_Test_ID = "ca-app-pub-3940256099942544/6300978111";

        internal const string Admob_Banner_ID = "ca-app-pub-2423762343641028/3717668211";

        internal const string Admob_App_ID = "ca-app-pub-2423762343641028~1199316087";
    }
}
