//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weigh.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weigh.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Activity.
        /// </summary>
        internal static string ActivityLevelLabel {
            get {
                return ResourceManager.GetString("ActivityLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Weight.
        /// </summary>
        internal static string AddEntryLabel {
            get {
                return ResourceManager.GetString("AddEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Weight Entry.
        /// </summary>
        internal static string AddEntryPageTitle {
            get {
                return ResourceManager.GetString("AddEntryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Weight Entry.
        /// </summary>
        internal static string AddNewEntryLabel {
            get {
                return ResourceManager.GetString("AddNewEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date:.
        /// </summary>
        internal static string AgeLabel {
            get {
                return ResourceManager.GetString("AgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 2 chars, max 3 chars.
        /// </summary>
        internal static string AgeLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("AgeLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be within range 1-150.
        /// </summary>
        internal static string AgeValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("AgeValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        internal static string BMILabel {
            get {
                return ResourceManager.GetString("BMILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Caloric Budget.
        /// </summary>
        internal static string BMRLabel {
            get {
                return ResourceManager.GetString("BMRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal.
        /// </summary>
        internal static string CaloriesToLoseWeightLabel {
            get {
                return ResourceManager.GetString("CaloriesToLoseWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal/Day to maintain weight.
        /// </summary>
        internal static string CaloriesToMaintainWeightLabel {
            get {
                return ResourceManager.GetString("CaloriesToMaintainWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Weight.
        /// </summary>
        internal static string CurrentWeightLabel {
            get {
                return ResourceManager.GetString("CurrentWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0:MM/dd/yyyy hh:mm}.
        /// </summary>
        internal static string DateLabelListviewItem {
            get {
                return ResourceManager.GetString("DateLabelListviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DayLabel {
            get {
                return ResourceManager.GetString("DayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string DaysLabel {
            get {
                return ResourceManager.GetString("DaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} Days to go.
        /// </summary>
        internal static string DaysToGoLabel {
            get {
                return ResourceManager.GetString("DaysToGoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left until goal.
        /// </summary>
        internal static string DaysUntilGoalLabel {
            get {
                return ResourceManager.GetString("DaysUntilGoalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Weight Entry.
        /// </summary>
        internal static string EditEntryPageTitle {
            get {
                return ResourceManager.GetString("EditEntryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing of info:.
        /// </summary>
        internal static string EnableEditSwitchLabel {
            get {
                return ResourceManager.GetString("EnableEditSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Entry:.
        /// </summary>
        internal static string EntryDateLabel {
            get {
                return ResourceManager.GetString("EntryDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleGenderSwitchLabel {
            get {
                return ResourceManager.GetString("FemaleGenderSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all forms!.
        /// </summary>
        internal static string FormValidationPopupLabel {
            get {
                return ResourceManager.GetString("FormValidationPopupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Date:.
        /// </summary>
        internal static string GoalDateEntryLabel {
            get {
                return ResourceManager.GetString("GoalDateEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Date: {0:MM/dd/yyyy}.
        /// </summary>
        internal static string GoalDateLabel {
            get {
                return ResourceManager.GetString("GoalDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Date.
        /// </summary>
        internal static string GoalDateSectionHeaderLabel {
            get {
                return ResourceManager.GetString("GoalDateSectionHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Info.
        /// </summary>
        internal static string GoalInfoLabel {
            get {
                return ResourceManager.GetString("GoalInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Status.
        /// </summary>
        internal static string GoalStatusLabel {
            get {
                return ResourceManager.GetString("GoalStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal date was too soon, and has been set to: {0:MM/dd/yy}.
        /// </summary>
        internal static string GoalTooSoonPopup {
            get {
                return ResourceManager.GetString("GoalTooSoonPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight:.
        /// </summary>
        internal static string GoalWeightEntryLabel {
            get {
                return ResourceManager.GetString("GoalWeightEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (lb).
        /// </summary>
        internal static string GoalWeightImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("GoalWeightImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight: {0:0.0}.
        /// </summary>
        internal static string GoalWeightLabel {
            get {
                return ResourceManager.GetString("GoalWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 chars, max 7 chars.
        /// </summary>
        internal static string GoalWeightLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("GoalWeightLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (kg).
        /// </summary>
        internal static string GoalWeightMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("GoalWeightMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight.
        /// </summary>
        internal static string GoalWeightSectionHeaderLabel {
            get {
                return ResourceManager.GetString("GoalWeightSectionHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be within range 0-1000.
        /// </summary>
        internal static string GoalWeightValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("GoalWeightValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Page.
        /// </summary>
        internal static string GraphPageTitle {
            get {
                return ResourceManager.GetString("GraphPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Exercise.
        /// </summary>
        internal static string HeavyActivityPickItem {
            get {
                return ResourceManager.GetString("HeavyActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height:.
        /// </summary>
        internal static string HeightLabel {
            get {
                return ResourceManager.GetString("HeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (ft).
        /// </summary>
        internal static string HeightMajorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in the range (1-15).
        /// </summary>
        internal static string HeightMajorImperialValidationErrorMessage {
            get {
                return ResourceManager.GetString("HeightMajorImperialValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 chars, max 5 chars.
        /// </summary>
        internal static string HeightMajorLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("HeightMajorLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (cm).
        /// </summary>
        internal static string HeightMajorMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in the range (50-300).
        /// </summary>
        internal static string HeightMajorMetricValidationErrorMessage {
            get {
                return ResourceManager.GetString("HeightMajorMetricValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (in).
        /// </summary>
        internal static string HeightMinorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMinorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} lb to go.
        /// </summary>
        internal static string ImperialWeightToGoLabel {
            get {
                return ResourceManager.GetString("ImperialWeightToGoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string InitialSetupPageTitle {
            get {
                return ResourceManager.GetString("InitialSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        internal static string KiloGramsLabel {
            get {
                return ResourceManager.GetString("KiloGramsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Level:.
        /// </summary>
        internal static string LevelOfActivityLabel {
            get {
                return ResourceManager.GetString("LevelOfActivityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Exercise.
        /// </summary>
        internal static string LightActivityPickItem {
            get {
                return ResourceManager.GetString("LightActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exercise.
        /// </summary>
        internal static string LowActivityPickItem {
            get {
                return ResourceManager.GetString("LowActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleGenderSwitchLabel {
            get {
                return ResourceManager.GetString("MaleGenderSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Exercise.
        /// </summary>
        internal static string MediumActivityPickItem {
            get {
                return ResourceManager.GetString("MediumActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0} kg to go.
        /// </summary>
        internal static string MetricWeightToGoLabel {
            get {
                return ResourceManager.GetString("MetricWeightToGoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string NameEntryPlaceholder {
            get {
                return ResourceManager.GetString("NameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry:.
        /// </summary>
        internal static string NewEntryLabel {
            get {
                return ResourceManager.GetString("NewEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal Weight.
        /// </summary>
        internal static string NormalWeightBMICategory {
            get {
                return ResourceManager.GetString("NormalWeightBMICategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string NormalWeightLabel {
            get {
                return ResourceManager.GetString("NormalWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Points:.
        /// </summary>
        internal static string NumberOfEntriesLabel {
            get {
                return ResourceManager.GetString("NumberOfEntriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obese.
        /// </summary>
        internal static string ObeseLabel {
            get {
                return ResourceManager.GetString("ObeseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obese.
        /// </summary>
        internal static string ObeseWeightBMICategory {
            get {
                return ResourceManager.GetString("ObeseWeightBMICategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off Schedule.
        /// </summary>
        internal static string OffScheduleLabel {
            get {
                return ResourceManager.GetString("OffScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Schedule.
        /// </summary>
        internal static string OnScheduleLabel {
            get {
                return ResourceManager.GetString("OnScheduleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        internal static string OverweightBMICategory {
            get {
                return ResourceManager.GetString("OverweightBMICategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        internal static string OverweightLabel {
            get {
                return ResourceManager.GetString("OverweightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}%.
        /// </summary>
        internal static string PercentLabel {
            get {
                return ResourceManager.GetString("PercentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        internal static string PoundsLabel {
            get {
                return ResourceManager.GetString("PoundsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ProgressLabel {
            get {
                return ResourceManager.GetString("ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight left to lose.
        /// </summary>
        internal static string RemainingWeightToLoseLabel {
            get {
                return ResourceManager.GetString("RemainingWeightToLoseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string SavedToast {
            get {
                return ResourceManager.GetString("SavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex:.
        /// </summary>
        internal static string SexLabel {
            get {
                return ResourceManager.GetString("SexLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month (31).
        /// </summary>
        internal static string ShowMonthGraphButton {
            get {
                return ResourceManager.GetString("ShowMonthGraphButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week (7).
        /// </summary>
        internal static string ShowWeekGraphButton {
            get {
                return ResourceManager.GetString("ShowWeekGraphButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year (365).
        /// </summary>
        internal static string ShowYearGraphButton {
            get {
                return ResourceManager.GetString("ShowYearGraphButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until: {0:MM/dd/yy}.
        /// </summary>
        internal static string TimeLeftLabel {
            get {
                return ResourceManager.GetString("TimeLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight lost to date.
        /// </summary>
        internal static string TotalWeightLostLabel {
            get {
                return ResourceManager.GetString("TotalWeightLostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Weight.
        /// </summary>
        internal static string UnderweightBMICategory {
            get {
                return ResourceManager.GetString("UnderweightBMICategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string UnderWeightLabel {
            get {
                return ResourceManager.GetString("UnderWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units:.
        /// </summary>
        internal static string UnitsLabel {
            get {
                return ResourceManager.GetString("UnitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string UnitSwitchImperialLabel {
            get {
                return ResourceManager.GetString("UnitSwitchImperialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string UnitSwitchMetricLabel {
            get {
                return ResourceManager.GetString("UnitSwitchMetricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        internal static string ValidationRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ValidationRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 2 chars, max 5 chars.
        /// </summary>
        internal static string WaistLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("WaistLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size:.
        /// </summary>
        internal static string WaistSizeEntryLabel {
            get {
                return ResourceManager.GetString("WaistSizeEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (in).
        /// </summary>
        internal static string WaistSizeImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("WaistSizeImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size.
        /// </summary>
        internal static string WaistSizeLabel {
            get {
                return ResourceManager.GetString("WaistSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size: {0}.
        /// </summary>
        internal static string WaistSizeLabelListviewItem {
            get {
                return ResourceManager.GetString("WaistSizeLabelListviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (cm).
        /// </summary>
        internal static string WaistSizeMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("WaistSizeMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be within range 15-200.
        /// </summary>
        internal static string WaistValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("WaistValueValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change from last entry: .
        /// </summary>
        internal static string WeightDeltaLabel {
            get {
                return ResourceManager.GetString("WeightDeltaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change from last entry: {0}.
        /// </summary>
        internal static string WeightDeltaLabelListviewItem {
            get {
                return ResourceManager.GetString("WeightDeltaLabelListviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight:.
        /// </summary>
        internal static string WeightEntryLabel {
            get {
                return ResourceManager.GetString("WeightEntryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (lb).
        /// </summary>
        internal static string WeightImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight: {0}.
        /// </summary>
        internal static string WeightLabelListviewItem {
            get {
                return ResourceManager.GetString("WeightLabelListviewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Goal Of: {0:0} lb.
        /// </summary>
        internal static string WeightLeftImperialLabel {
            get {
                return ResourceManager.GetString("WeightLeftImperialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Goal Of: {0:0} kg.
        /// </summary>
        internal static string WeightLeftMetricLabel {
            get {
                return ResourceManager.GetString("WeightLeftMetricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 1 chars, max 7 chars.
        /// </summary>
        internal static string WeightLengthValidationErrorMessage {
            get {
                return ResourceManager.GetString("WeightLengthValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        internal static string WeightMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be within range 0-1000.
        /// </summary>
        internal static string WeightValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("WeightValueValidationErrorMessage", resourceCulture);
            }
        }
    }
}
