//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weigh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weigh.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Height (ft) Here.
        /// </summary>
        internal static string HeightMajorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Height (cm) Here.
        /// </summary>
        internal static string HeightMajorMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (in).
        /// </summary>
        internal static string HeightMinorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMinorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Age Here.
        /// </summary>
        internal static string NameEntryPlaceholder {
            get {
                return ResourceManager.GetString("NameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (in).
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Exercise.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Exercise.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Exercise.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all forms!.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight lost to date: .
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMR (Calories/Day).
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal/Day to lose weight.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cal/Day to maintain weight.
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (cm).
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Weight left to lose.
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Date.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left until goal = .
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI - .
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obese.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Activity.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight: .
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change from last entry: .
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Page.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing of info:.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (lb).
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (kg).
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exercise.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string UnitSwitchImperialLabel {
            get {
                return ResourceManager.GetString("UnitSwitchImperialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string UnitSwitchMetricLabel {
            get {
                return ResourceManager.GetString("UnitSwitchMetricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (lb).
        /// </summary>
        internal static string WeightImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        internal static string WeightMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightMetricEntryPlaceholder", resourceCulture);
            }
        }
    }
}
