//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weigh {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weigh.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of Activity.
        /// </summary>
        internal static string ActivityLevelLabel {
            get {
                return ResourceManager.GetString("ActivityLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI - .
        /// </summary>
        internal static string BMILabel {
            get {
                return ResourceManager.GetString("BMILabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMR (Calories/Day).
        /// </summary>
        internal static string BMRLabel {
            get {
                return ResourceManager.GetString("BMRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cal/Day to lose weight.
        /// </summary>
        internal static string CaloriesToLoseWeightLabel {
            get {
                return ResourceManager.GetString("CaloriesToLoseWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cal/Day to maintain weight.
        /// </summary>
        internal static string CaloriesToMaintainWeightLabel {
            get {
                return ResourceManager.GetString("CaloriesToMaintainWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: .
        /// </summary>
        internal static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days left until goal = .
        /// </summary>
        internal static string DaysUntilGoalLabel {
            get {
                return ResourceManager.GetString("DaysUntilGoalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Editing of info:.
        /// </summary>
        internal static string EnableEditSwitchLabel {
            get {
                return ResourceManager.GetString("EnableEditSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FemaleGenderSwitchLabel {
            get {
                return ResourceManager.GetString("FemaleGenderSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all forms!.
        /// </summary>
        internal static string FormValidationPopupLabel {
            get {
                return ResourceManager.GetString("FormValidationPopupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Date.
        /// </summary>
        internal static string GoalDateLabel {
            get {
                return ResourceManager.GetString("GoalDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (lb).
        /// </summary>
        internal static string GoalWeightImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("GoalWeightImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight.
        /// </summary>
        internal static string GoalWeightLabel {
            get {
                return ResourceManager.GetString("GoalWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Weight (kg).
        /// </summary>
        internal static string GoalWeightMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("GoalWeightMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph Page.
        /// </summary>
        internal static string GraphPageTitle {
            get {
                return ResourceManager.GetString("GraphPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Exercise.
        /// </summary>
        internal static string HeavyActivityPickItem {
            get {
                return ResourceManager.GetString("HeavyActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Height (ft) Here.
        /// </summary>
        internal static string HeightMajorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Height (cm) Here.
        /// </summary>
        internal static string HeightMajorMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMajorMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (in).
        /// </summary>
        internal static string HeightMinorImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("HeightMinorImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string InitialSetupPageTitle {
            get {
                return ResourceManager.GetString("InitialSetupPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Exercise.
        /// </summary>
        internal static string LightActivityPickItem {
            get {
                return ResourceManager.GetString("LightActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exercise.
        /// </summary>
        internal static string LowActivityPickItem {
            get {
                return ResourceManager.GetString("LowActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MaleGenderSwitchLabel {
            get {
                return ResourceManager.GetString("MaleGenderSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate Exercise.
        /// </summary>
        internal static string MediumActivityPickItem {
            get {
                return ResourceManager.GetString("MediumActivityPickItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Age Here.
        /// </summary>
        internal static string NameEntryPlaceholder {
            get {
                return ResourceManager.GetString("NameEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string NormalWeightLabel {
            get {
                return ResourceManager.GetString("NormalWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obese.
        /// </summary>
        internal static string ObeseLabel {
            get {
                return ResourceManager.GetString("ObeseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        internal static string OverweightLabel {
            get {
                return ResourceManager.GetString("OverweightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Weight left to lose.
        /// </summary>
        internal static string RemainingWeightToLoseLabel {
            get {
                return ResourceManager.GetString("RemainingWeightToLoseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight lost to date: .
        /// </summary>
        internal static string TotalWeightLostLabel {
            get {
                return ResourceManager.GetString("TotalWeightLostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underweight.
        /// </summary>
        internal static string UnderWeightLabel {
            get {
                return ResourceManager.GetString("UnderWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        internal static string UnitSwitchImperialLabel {
            get {
                return ResourceManager.GetString("UnitSwitchImperialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        internal static string UnitSwitchMetricLabel {
            get {
                return ResourceManager.GetString("UnitSwitchMetricLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (in).
        /// </summary>
        internal static string WaistSizeImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("WaistSizeImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waist Size (cm).
        /// </summary>
        internal static string WaistSizeMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("WaistSizeMetricEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change from last entry: .
        /// </summary>
        internal static string WeightDeltaLabel {
            get {
                return ResourceManager.GetString("WeightDeltaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (lb).
        /// </summary>
        internal static string WeightImperialEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightImperialEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (kg).
        /// </summary>
        internal static string WeightMetricEntryPlaceholder {
            get {
                return ResourceManager.GetString("WeightMetricEntryPlaceholder", resourceCulture);
            }
        }
    }
}
